# This is a basic workflow to help you get started with Actions

name: Recompile LaTeX files

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events on the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  compile_latex:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository 
      - uses: actions/checkout@v2
        
      - uses: dorny/paths-filter@v2.2.1
        id: filter
        with:
          filters: |
            stadgar:
              - 'stadgar/stadgar.tex'
            reglemente:
              - 'reglemente/reglemente.tex'
            eko_reglemente:
              - 'ekonomiskt_reglemente/ekonomiskt_reglemente.tex'
                
      - name: Checkout stadgar
        if: steps.filter.outputs.stadgar == 'true'
        uses: actions/checkout@v2
        with:
          repository: dtekcth/dTeX
          path: stadgar
      - name: Kompilera stadgar
        if: steps.filter.outputs.stadgar == 'true'
        uses: vinay0410/tectonic-action@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Path of Tex File
          tex_path: 'stadgar/stadgar.tex'
          # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
          push: 'yes'
          
      - name: Checkout reglemente
        if: steps.filter.outputs.reglemente == 'true'
        uses: actions/checkout@v2
        with:
          repository: dtekcth/dTeX
          path: reglemente
      - name: Kompilera reglemente
        if: steps.filter.outputs.reglemente == 'true'
        uses: vinay0410/tectonic-action@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Path of Tex File
          tex_path: 'reglemente/reglemente.tex'
          # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
          push: 'yes'
          
      - name: Checkout ekonomiskt reglemente
        if: steps.filter.outputs.ekonomiskt_reglemente == 'true'
        uses: actions/checkout@v2
        with:
          repository: dtekcth/dTeX
          path: ekonomiskt_reglemente
      - name: Kompilera ekonomiskt reglemente
        if: steps.filter.outputs.ekonomiskt_reglemente == 'true'
        uses: vinay0410/tectonic-action@v1.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Path of Tex File
          tex_path: 'ekonomiskt_reglemente/ekonomiskt_reglemente.tex'
          # String stating whether to push output PDF, PDF will only be pushed in case of "yes"
          push: 'yes'
